"""create roles, permissions & join tables (add user field) 

Revision ID: 8a561e85a7c2
Revises: ca66ef3bc22e
Create Date: 2025-07-27 20:54:57.023528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a561e85a7c2'
down_revision: Union[str, Sequence[str], None] = 'ca66ef3bc22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
